version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
      - ./video_history.db:/app/video_history.db
    env_file:
      - .env
    restart: unless-stopped
